import type { ProductRecommendation } from "./types"

export const skincareCatalog: ProductRecommendation[] = [
  {
    id: "p1",
    name: "Hydra Boost Gel Cream",
    brand: "Aqua Essentials",
    category: "Moisturizer",
    description: "Lightweight gel-cream that provides 24-hour hydration with hyaluronic acid for dehydrated skin.",
    price: 24.99,
    imageUrl: "/placeholder.svg?height=300&width=300",
    keyIngredients: ["Hyaluronic Acid", "Glycerin", "Dimethicone", "Aloe Vera"],
    skinConcerns: ["dry", "dehydrated", "sensitive"],
  },
  {
    id: "p2",
    name: "Clear Pore BHA Liquid",
    brand: "Skin Clarity",
    category: "Exfoliant",
    description: "Leave-on exfoliant that unclogs pores, prevents breakouts, and smooths skin texture.",
    price: 29.99,
    imageUrl: "/placeholder.svg?height=300&width=300",
    keyIngredients: ["Salicylic Acid (2%)", "Green Tea Extract", "Methylpropanediol"],
    skinConcerns: ["acne", "oily", "combination"],
  },
  {
    id: "p3",
    name: "Vitamin C Brightening Serum",
    brand: "Glow Theory",
    category: "Serum",
    description:
      "Potent antioxidant serum that brightens skin tone, reduces dark spots, and boosts collagen production.",
    price: 38.5,
    imageUrl: "/placeholder.svg?height=300&width=300",
    keyIngredients: ["Vitamin C (15%)", "Ferulic Acid", "Vitamin E", "Hyaluronic Acid"],
    skinConcerns: ["dull", "pigmentation", "aging"],
  },
  {
    id: "p4",
    name: "Barrier Repair Cream",
    brand: "Derma Defense",
    category: "Moisturizer",
    description: "Rich cream that restores the skin barrier with ceramides and fatty acids for extremely dry skin.",
    price: 32.0,
    imageUrl: "/placeholder.svg?height=300&width=300",
    keyIngredients: ["Ceramides", "Niacinamide", "Fatty Acids", "Shea Butter"],
    skinConcerns: ["dry", "sensitive", "dehydrated"],
  },
  {
    id: "p5",
    name: "Retinol Renewal Night Cream",
    brand: "Age Defiance",
    category: "Treatment",
    description: "Advanced night treatment that reduces fine lines and wrinkles while improving skin texture.",
    price: 45.99,
    imageUrl: "/placeholder.svg?height=300&width=300",
    keyIngredients: ["Retinol (0.5%)", "Peptides", "Squalane", "Niacinamide"],
    skinConcerns: ["aging", "dull", "pigmentation"],
  },
  {
    id: "p6",
    name: "Oil Control Mattifying Gel",
    brand: "Matte Perfection",
    category: "Moisturizer",
    description: "Oil-free gel moisturizer that controls shine and minimizes the appearance of pores.",
    price: 26.5,
    imageUrl: "/placeholder.svg?height=300&width=300",
    keyIngredients: ["Niacinamide", "Zinc PCA", "Salicylic Acid", "Hyaluronic Acid"],
    skinConcerns: ["oily", "combination", "acne"],
  },
  {
    id: "p7",
    name: "Soothing Centella Toner",
    brand: "Calm Collective",
    category: "Toner",
    description: "Alcohol-free toner that calms irritation, reduces redness, and hydrates sensitive skin.",
    price: 22.0,
    imageUrl: "/placeholder.svg?height=300&width=300",
    keyIngredients: ["Centella Asiatica", "Panthenol", "Allantoin", "Glycerin"],
    skinConcerns: ["sensitive", "redness", "dry"],
  },
  {
    id: "p8",
    name: "AHA Resurfacing Treatment",
    brand: "Skin Renewal",
    category: "Exfoliant",
    description: "Weekly treatment that exfoliates dead skin cells to reveal brighter, smoother skin.",
    price: 34.99,
    imageUrl: "/placeholder.svg?height=300&width=300",
    keyIngredients: ["Glycolic Acid (10%)", "Lactic Acid", "Licorice Root Extract", "Aloe Vera"],
    skinConcerns: ["dull", "pigmentation", "aging"],
  },
  {
    id: "p9",
    name: "Hydrating Cleansing Gel",
    brand: "Pure Balance",
    category: "Cleanser",
    description: "Gentle gel cleanser that removes impurities without stripping the skin's natural moisture.",
    price: 18.99,
    imageUrl: "/placeholder.svg?height=300&width=300",
    keyIngredients: ["Glycerin", "Coco-Glucoside", "Aloe Vera", "Panthenol"],
    skinConcerns: ["combination", "sensitive", "dry"],
  },
  {
    id: "p10",
    name: "Niacinamide Pore Refining Serum",
    brand: "Pore Perfector",
    category: "Serum",
    description: "Concentrated serum that minimizes pores, regulates sebum, and improves skin texture.",
    price: 28.5,
    imageUrl: "/placeholder.svg?height=300&width=300",
    keyIngredients: ["Niacinamide (10%)", "Zinc PCA", "Hyaluronic Acid", "Panthenol"],
    skinConcerns: ["oily", "combination", "acne"],
  },
  {
    id: "p11",
    name: "Ultra Gentle Moisturizing Cream",
    brand: "Sensitive Solution",
    category: "Moisturizer",
    description: "Fragrance-free cream specially formulated for reactive and easily irritated skin.",
    price: 27.0,
    imageUrl: "/placeholder.svg?height=300&width=300",
    keyIngredients: ["Colloidal Oatmeal", "Ceramides", "Allantoin", "Squalane"],
    skinConcerns: ["sensitive", "redness", "dry"],
  },
  {
    id: "p12",
    name: "Peptide Firming Eye Cream",
    brand: "Eye Revival",
    category: "Eye Care",
    description: "Advanced eye treatment that targets fine lines, puffiness, and dark circles.",
    price: 36.99,
    imageUrl: "/placeholder.svg?height=300&width=300",
    keyIngredients: ["Peptides", "Caffeine", "Niacinamide", "Hyaluronic Acid"],
    skinConcerns: ["aging", "dull", "sensitive"],
  },
]
